### ISSUE TITLE
Additional events

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-net#25]
For example:

* `DialAddr(peer, multiaddr)`
* `Dial(peer)`
* `Error(type, peer, multiaddr)`

**Comment by iulianpascalau** [comment]
I wish to have something like `Connecting(Network, Conn) bool` that will either permit the connection to be made or simply denying the connection. (Since there can be more notifee objects, the resulting action can have some logic behind like: if one notifee returned false, the connection will abort, if there are no notifees, permit all peers to connect). 
This might prove useful when trying to forbid some peers to connect to current node. The reason for this "denial" can be: to many connections, the peer has bad reputation or to slow, and so on.
Implementing a "quite dummy" node bootstrapper, I found out that one peer successfully connects to other peer just to find out that the other peer closed the connection after a couple of ms

**Comment by makew0rld** [comment]
This would close https://github.com/ipfs/go-ipfs/issues/1972

**Comment by Stebalien** [comment]
https://github.com/libp2p/go-libp2p/issues/653
